services:
  web:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - todo

  todo:
    build:
      context: ./
      dockerfile: ./apps/todo/Dockerfile
    stop_signal: SIGKILL
    restart: always
