services:
  web: 
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./config/nginx:/etc/nginx:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro

  todo:
    build:
      context: ./
      dockerfile: ./apps/todo/Dockerfile
    restart: unless-stopped


  next:
    build:
      context: ./
      dockerfile: ./apps/next/Dockerfile
    restart: unless-stopped
