services:
  web: 
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro

  todo:
    build:
      context: ./
      dockerfile: ./apps/todo/Dockerfile
    restart: unless-stopped
